Numpy provides Array Structur And optimized Numerical Operation, which make it core library for Data science And Machine Learning

In [ ]:
import numpy as np

arr = np.arange(1, 26).reshape(5,5)

print(arr)

Tasks

Extract the center 3×3 submatrix
Extract all elements greater than 15
Replace all even numbers with 0
Get the diagonal elements

In [ ]:
import numpy as np

arr = np.arange(1, 26).reshape(5,5)

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [27]:
center = arr[0:4,0:4]

print(center)

[[ 1  2  3  4]
 [ 6  7  8  9]
 [11 12 13 14]
 [16 17 18 19]]


In [28]:
greater_than_15 = arr[arr>15]
print(greater_than_15)

[16 17 18 19 20 21 22 23 24 25]


In [34]:
arr_even_replace = arr.copy()
arr_even_replace[ arr_even_replace % 2 ==0] = 0
print(arr_even_replace)

[[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]


In [35]:
diagonal_elements = np.diag(arr)
print("\nDiagonal elements:\n", diagonal_elements)


Diagonal elements:
 [ 1  7 13 19 25]
